# show gekko verbose (strat info) - gekko must start with -d flag;
gekkoDebug = 0
# time window size on days of candlesticks for each evaluation
deltaDays = 90
# candle size for gekko backtest in minutes
candleSize = 10
# mode of profit interpretation = v1, v2 or v3.
# please check the first functions at evaluation.gekko.backtest
# to understand what is this. has big impact on evolutionary agenda.
interpreteBacktestProfit = 'v3'
# Number of candlestick data loaded simultaneously in each locale;
# slower EPOCHS theoretical better evolution;
# seems broken. values other than 1 makes evolution worse.
ParallelCandlestickDataset = 1
# number of parallel backtests running on gekko;
ParallelBacktests = 6


