version: '3'
services:
  gekko:
    image: gekko
    volumes:
      - gekko-dir:/usr/src/app
    ports:
      - "3000:3000"
  japonicus:
    command: $JARGS
    
    image: japonicus
    build: .
    volumes:
      - gekko-dir:/root/gekko
    ports:
      - "5000:5000"

    depends_on:
      - gekko

volumes:
  gekko-dir:
