# MAJOR SMA TRENDS
MAJOR_SMA_long = 2000
MAJOR_SMA_short = 500

# MAJOR BULL TREND
# SMA Trends
BULL__SMA_long = 1000
BULL__SMA_short = 50
# BULL
BULL__BULL_RSI = 10
BULL__BULL_RSI_high = 80
BULL__BULL_RSI_low = 60
# BEAR
BULL__BEAR_RSI = 15
BULL__BEAR_RSI_high = 50
BULL__BEAR_RSI_low = 20

# MAJOR BEAR TREND
# SMA Trends
BEAR__SMA_long = 1000
BEAR__SMA_short = 50
# BULL
BEAR__BULL_RSI = 10
BEAR__BULL_RSI_high = 80
BEAR__BULL_RSI_low = 60
# BEAR
BEAR__BEAR_RSI = 15
BEAR__BEAR_RSI_high = 50
BEAR__BEAR_RSI_low = 20

